encyclopedia/urls.py
from django.urls import path

from . import views


app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.title_to_display, name="title_to_display"),
    path("new_page", views.new_page, name="new_page"),
    path("edit_page", views.edit_page, name="edit_page"),
    path("random_entry", views.random_entry, name="random_entry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import HttpResponse, render, HttpResponseRedirect
from markdown2 import Markdown
from django import forms
from . import util
import random




class NewTitleForm(forms.Form):
    title_entry_add = forms.CharField(required=True)
    description_add = forms.CharField(label = "Add Description", widget=forms.Textarea(attrs={"rows":2, "cols":10}), required=True)


def index(request):
    case_matching_list = []
    lower_case_list_entries = []
    if request.method == 'POST':
        substring = request.POST.get('q').lower()
        lower_case_list_entries = [item.lower() for item in util.list_entries()]
        case_matching_list = [i for i in lower_case_list_entries if substring in i]
        #print(case_matching_list)
        if len(case_matching_list) == 1:
            return HttpResponseRedirect("/wiki/" + case_matching_list[0])
        elif len(case_matching_list) > 1:
            return render(request, "encyclopedia/index.html", {
                "entries": [item.capitalize() for item in case_matching_list]
            })
        else:
            return render(request, "encyclopedia/error.html")

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def title_to_display(request, title):
    if request.method == 'POST':
        content = util.get_entry(title)
        form = NewTitleForm(request.POST)
        if form.is_valid():
            util.save_entry(form.cleaned_data['title_entry_add'], form.cleaned_data['description_add'])
            # return render(request, "encyclopedia/error.html", {
            #     "item_to_display": markdowner.convert(util.get_entry(title))
            # })
    else:
        entry_check = util.get_entry(title)
        if entry_check is None:
            return render(request, "encyclopedia/error.html")

    markdowner = Markdown()
    markdowner.convert(util.get_entry(title))

    return render(request, "encyclopedia/title.html", {
        "item_to_display": markdowner.convert(util.get_entry(title))
        })


def new_page(request):
    if request.method == 'POST':
        entryForm = NewTitleForm(request.POST)
        if entryForm.is_valid():
            #print(entryForm.cleaned_data)
            if entryForm.cleaned_data['title_entry_add'].lower() not in [item.lower() for item in util.list_entries()]:
                util.save_entry(entryForm.cleaned_data['title_entry_add'], entryForm.cleaned_data['description_add'])
                return HttpResponseRedirect("/wiki/" + entryForm.cleaned_data['title_entry_add'])
            else:
                return render(request, "encyclopedia/duplicate_entry.html")
        else:
            entryForm = NewTitleForm()

    return render(request, "encyclopedia/new_page.html", {
        "title_entry_form": NewTitleForm()
    })

def edit_page(request):
    if request.method == 'POST':
        title = request.META.get('HTTP_REFERER').split('/')[-1]
        content = util.get_entry(title)
        print(content)
        form = NewTitleForm(initial={'title_entry_add': title,'description_add':content})
        return render(request, 'encyclopedia/edit_page.html',{
            "edit_form": form,
            "title":title
        })

def random_entry(request):
    title = random.choice(util.list_entries())
    return HttpResponseRedirect("/wiki/" + title)



    


    

encyclopedia/templates/encyclopedia/duplicate_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1>Entry Already Exists</h1>

{% endblock %}

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <form action="{% url 'encyclopedia:title_to_display' title=title %}" method="post">
        {% csrf_token %}
        {{ edit_form }}
    <input type="submit" value="Edit">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1>Requested Page was Not Found</h1>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{entry}}">{{ entry }}</li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    <!-- {{form}} -->
                    <input type="submit" value="Submit">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}"> Create New Page </a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_entry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Title</h1>

    <form action="{% url 'encyclopedia:new_page' %}" method="post">
    {% csrf_token %}

    {{title_entry_form}}

    <input type="submit" value="Save">

    </form>




{% endblock %}

encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    {{item_to_display|safe}}
    
    <form action="{% url 'encyclopedia:edit_page' %}" method="post">
        {% csrf_token %}
    <input type="submit" value="Edit">
    </form>

{% endblock %}